# Generated by Django 6.0.4 on 2026-05-04 17:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('descricao', models.TextField(blank=True)),
                ('total_vagas', models.PositiveIntegerField(default=10)),
            ],
        ),
        migrations.CreateModel(
            name='Candidato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('cpf', models.CharField(max_length=14)),
                ('tipo', models.IntegerField(choices=[(1, 'Cotista'), (2, 'Ampla Concorrência')], default=2)),
                ('status', models.CharField(choices=[('espera', 'Em Espera'), ('aprovado', 'Aprovado')], default='espera', max_length=10)),
                ('data_inscricao', models.DateTimeField(auto_now_add=True)),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='candidatos', to='vagas.curso')),
            ],
            options={
                'ordering': ['tipo', 'data_inscricao'],
                'unique_together': {('curso', 'cpf')},
            },
        ),
    ]
